import tempfile
import uuid
from pathlib import Path
import fitz          # PyMuPDF — converts PDF pages to images for Gemini Vision
import pdfplumber    # extracts text, tables, and bounding box coordinates


def process(file_content: bytes, job_id: str, filename: str) -> dict:
    """
    Main entry point for the Diagrams/Tables modality.
    Called by app.py when a document is uploaded.

    Args:
        file_content : raw bytes of the uploaded PDF
        job_id       : unique ID generated by app.py for this job
        filename     : original filename of the uploaded PDF

    Returns:
        dict with pages, tables, page_images, and mock annotations
    """

    # Write the PDF bytes to a temp file so pdfplumber and fitz can open it
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp:
        temp_path = temp.name
        temp.write(file_content)

    try:
        pages        = []
        tables       = []
        page_images  = []

        # ── STAGE 1: pdfplumber — text, bounding boxes, tables ────────────
        with pdfplumber.open(temp_path) as pdf:
            for i, page in enumerate(pdf.pages):

                # Extract full page text as a single string
                text = page.extract_text() or ""

                # Extract every word with its bounding box
                # Coordinates normalized to 0–1 range (% of page dimensions)
                # so the frontend can position highlights on any screen size
                words = [
                    {
                        "text": w["text"],
                        "x0":   round(w["x0"]    / page.width,  4),
                        "y0":   round(w["top"]    / page.height, 4),
                        "x1":   round(w["x1"]     / page.width,  4),
                        "y1":   round(w["bottom"] / page.height, 4),
                    }
                    for w in page.extract_words()
                ]

                pages.append({
                    "page_num": i + 1,
                    "text":     text,
                    "words":    words,
                })

                # Extract tables — this is the core of this modality
                # Returns a list of 2D arrays: [["Header1","Header2"],["val1","val2"]]
                raw_tables = page.extract_tables()
                for table in raw_tables:
                    tables.append({
                        "page_num": i + 1,
                        "data":     table,
                    })

        # ── STAGE 2: PyMuPDF — render each page as image ──────────────────
        # These PNG images will be sent to Gemini Vision in Milestone 2
        # for diagram detection and analysis
        doc = fitz.open(temp_path)
        for page_num in range(len(doc)):
            pix = doc[page_num].get_pixmap()
            page_images.append({
                "page_num": page_num + 1,
                "width":    pix.width,
                "height":   pix.height,
                # pix.tobytes("png") will be passed to Gemini Vision in M2
            })
        doc.close()

        # ── STAGE 3: Mock annotations ──────────────────────────────────────
        # Placeholder for real Gemini feedback — arrives in Milestone 2
        # Schema is identical to what the real Gemini service will return
        # so the frontend can be built against this now without waiting for keys
        mock_annotations = [
            {
                "id":           f"annotation-{job_id[:8]}-001",
                "page":         1,
                "bbox":         {
                    "x":      0.1,
                    "y":      0.2,
                    "width":  0.8,
                    "height": 0.05
                },
                "region_type":  "paragraph",
                "feedback":     "Good structure, but the argument needs more supporting evidence.",
                "confidence":   0.87,
                "needs_review": False,
            }
        ]

        return {
            "job_id":      job_id,
            "status":      "done",
            "filename":    filename,
            "page_count":  len(pages),
            "table_count": len(tables),
            "pages":       pages,
            "tables":      tables,
            "page_images": page_images,
            "annotations": mock_annotations,
        }

    finally:
        # Always delete the temp file even if something crashes above
        Path(temp_path).unlink(missing_ok=True)